#!/usr/bin/env python3
"""Generate a C scaler header from a saved StandardScaler + feature names JSON."""

import sys
sys.path.insert(0, '/Users/loganluna/VSCode/SatelliteAnomalyDetection/intrusion_detection')

import argparse
import joblib, json
import numpy as np
from pathlib import Path

MODELS_DIR = Path('/Users/loganluna/VSCode/SatelliteAnomalyDetection/intrusion_detection/models/trained_models')


def build_header_lines(names, mean, scale):
    n = len(names)
    lines = [
        '/* Auto-generated by generate_scaler_header.py — DO NOT EDIT */',
        '#pragma once',
        '#include <stdint.h>',
        '',
        f'#define IDS_N_FEATURES {n}',
        '',
        '/* Feature index constants */',
    ]
    for i, name in enumerate(names):
        lines.append(f'#define IDS_FEAT_{name.upper():30s} {i}')

    lines += [
        '',
        '/* StandardScaler parameters (fit on training data) */',
        f'static const float ids_scaler_mean[{n}] = {{',
        '    ' + ', '.join(f'{v:.6f}f' for v in mean),
        '};',
        '',
        f'static const float ids_scaler_scale[{n}] = {{',
        '    ' + ', '.join(f'{v:.6f}f' for v in scale),
        '};',
        '',
        '/* Apply StandardScaler in-place to a raw feature vector */',
        'static inline void ids_scale_features(float *x) {',
        '    for (int i = 0; i < IDS_N_FEATURES; i++) {',
        '        x[i] = (x[i] - ids_scaler_mean[i]) / ids_scaler_scale[i];',
        '    }',
        '}',
    ]
    return lines


def main():
    ap = argparse.ArgumentParser(description='Generate scaler header from joblib scaler')
    ap.add_argument('--scaler', default=str(MODELS_DIR / 'can_scaler.joblib'))
    ap.add_argument('--features', default=str(MODELS_DIR / 'can_feature_names.json'))
    ap.add_argument('--out', default=str(MODELS_DIR / 'stm32h7_can_ids_scaler.h'))
    args = ap.parse_args()

    scaler = joblib.load(Path(args.scaler))
    with open(Path(args.features)) as f:
        names = json.load(f)

    mean  = scaler.mean_.astype(np.float32)
    scale = scaler.scale_.astype(np.float32)
    lines = build_header_lines(names, mean, scale)

    out = Path(args.out)
    out.write_text('\n'.join(lines) + '\n')
    print(f'Written -> {out}')
    print(f'  {len(names)} features, mean range [{mean.min():.3f}, {mean.max():.3f}]')

if __name__ == '__main__':
    main()
