"""
cwl_export.py — Generate CWL (Common Workflow Language) files from components.json.

Produces:
  <output_dir>/
    workflow.cwl          — top-level CWL Workflow connecting M1→M5 (+ E1/E2)
    tools/<module_id>.cwl — one CommandLineTool per module

CWL v1.2 used throughout.  Tool stubs use `baseCommand: python` and pass
the module's script_path (from workflow.py) as the first argument.

Usage
-----
  python -m scripts.utils.cwl_export
  python -m scripts.utils.cwl_export --components components.json --output cwl/
"""

from __future__ import annotations

import argparse
import json
import os
import re
from typing import Any


# ── Helpers ───────────────────────────────────────────────────────────────────

def _safe_id(s: str) -> str:
    return re.sub(r"[^a-zA-Z0-9_]", "_", s)


def _cwl_type(json_type: str) -> str:
    mapping = {
        "str": "string", "string": "string",
        "int": "int",    "integer": "int",
        "float": "float", "double": "float",
        "bool": "boolean", "boolean": "boolean",
        "list": "string[]",
        "dict": "string",       # JSON-encoded dict passed as string
        "path": "File",
        "file_path_or_dir": "File",
        "pd.DataFrame": "File", # represented as CSV file on disk
        "np.ndarray": "File",   # represented as numpy .npy file on disk
        "dict/JSON": "File",
        "list[str]": "string[]",
        "list[dict]": "File",   # JSON file
        "list[path]": "File[]",
        "RDF/Turtle": "File",
        "GraphML": "File",
        "CSV": "File",
        "Markdown": "File",
        "JSON": "File",
    }
    for k, v in mapping.items():
        if k.lower() in json_type.lower():
            return v
    return "string"


def _make_tool_cwl(module: dict[str, Any], script_path: str | None) -> str:
    """Generate a CommandLineTool CWL document for one module."""
    mod_id    = module["id"]
    mod_label = module.get("label", mod_id)
    mod_desc  = module.get("description", "")
    cmd       = script_path or f"scripts/run_{mod_id.lower()}.py"

    inputs_block  = _tool_inputs(module.get("inputs", []))
    outputs_block = _tool_outputs(module.get("outputs", []))
    hints_block   = _hints_block(module.get("config_params", []))

    return f"""\
#!/usr/bin/env cwl-runner
# CWL v1.2 CommandLineTool — {mod_label}
# Auto-generated by scripts/utils/cwl_export.py

cwlVersion: v1.2
class: CommandLineTool

label: "{mod_label}"
doc: >
  {mod_desc}

baseCommand: [python, "{cmd}"]

requirements:
  NetworkAccess:
    networkAccess: false

hints:
  SoftwareRequirement:
    packages:
      - package: sensorwf
        version: ["1.0.0"]

inputs:
{inputs_block}

outputs:
{outputs_block}
{hints_block}
"""


def _tool_inputs(ports: list[dict[str, Any]]) -> str:
    if not ports:
        return "  {}"
    lines: list[str] = []
    for port in ports:
        name = _safe_id(port.get("name", "input"))
        ptype = _cwl_type(port.get("type", "string"))
        desc  = port.get("description", "").replace('"', "'")
        lines.append(f"  {name}:")
        lines.append(f"    type: {ptype}")
        if desc:
            lines.append(f'    doc: "{desc}"')
        lines.append(f"    inputBinding:")
        lines.append(f"      prefix: --{name.replace('_', '-')}")
    return "\n".join(lines)


def _tool_outputs(ports: list[dict[str, Any]]) -> str:
    if not ports:
        return "  {}"
    lines: list[str] = []
    for port in ports:
        name  = _safe_id(port.get("name", "output"))
        ptype = _cwl_type(port.get("type", "File"))
        # Normalise to a file output for CWL purposes
        if "[]" not in ptype:
            ptype = "File"
        desc = port.get("description", "").replace('"', "'")
        lines.append(f"  {name}:")
        lines.append(f"    type: {ptype}")
        if desc:
            lines.append(f'    doc: "{desc}"')
        lines.append(f"    outputBinding:")
        lines.append(f"      glob: '{name}*'")
    return "\n".join(lines)


def _hints_block(config_params: list[dict[str, Any]]) -> str:
    if not config_params:
        return ""
    lines = ["", "# Config parameters (passed as --key value at runtime)"]
    lines.append("# Defaults:")
    for p in config_params:
        name    = p.get("name", "")
        default = p.get("default")
        desc    = p.get("description", "")
        if default is not None:
            lines.append(f"#   --{name.replace('_', '-')} {default}  # {desc}")
    return "\n".join(lines) + "\n"


def _make_workflow_cwl(
    modules: list[dict[str, Any]],
    tool_dir: str = "tools",
) -> str:
    """Generate a top-level Workflow CWL document linking all steps."""
    core_mods = [m for m in modules if not m.get("extension", False)]
    ext_mods  = [m for m in modules if m.get("extension", False)]
    ordered   = core_mods + ext_mods  # M1→M5→E1→E2

    # Build global inputs: the union of all module inputs that are not
    # satisfied by a prior module's output (i.e., source = "workflow")
    output_names: set[str] = set()
    wf_inputs:    list[dict] = []
    for mod in ordered:
        for port in mod.get("inputs", []):
            pname = _safe_id(port.get("name", ""))
            if pname not in output_names:
                wf_inputs.append({
                    "name":  pname,
                    "type":  _cwl_type(port.get("type", "string")),
                    "doc":   port.get("description", ""),
                })
        for port in mod.get("outputs", []):
            output_names.add(_safe_id(port.get("name", "")))

    # Workflow inputs block
    wi_lines: list[str] = []
    seen_wi: set[str] = set()
    for wi in wf_inputs:
        if wi["name"] in seen_wi:
            continue
        seen_wi.add(wi["name"])
        t = wi["type"]
        # Wrap optional inputs as optional
        wi_lines.append(f"  {wi['name']}:")
        wi_lines.append(f"    type: [{t}, \"null\"]")
        if wi["doc"]:
            wi_lines.append(f'    doc: "{wi["doc"].replace(chr(34), chr(39))}"')

    # Workflow outputs block: last module's outputs
    last_mod = ordered[-1] if ordered else None
    wo_lines: list[str] = []
    if last_mod:
        step_id = _safe_id(last_mod["id"])
        for port in last_mod.get("outputs", []):
            pname = _safe_id(port.get("name", "output"))
            wo_lines.append(f"  {pname}:")
            wo_lines.append(f"    type: File")
            wo_lines.append(f"    outputSource: {step_id}/{pname}")

    # Steps block
    step_lines: list[str] = []
    prev_outputs: dict[str, str] = {}  # port_name → step_id/port_name
    for mod in ordered:
        step_id  = _safe_id(mod["id"])
        tool_ref = f"{tool_dir}/{mod['id']}.cwl"

        # Step inputs: wire from previous outputs or from workflow inputs
        in_lines: list[str] = []
        for port in mod.get("inputs", []):
            pname = _safe_id(port.get("name", ""))
            source = prev_outputs.get(pname, pname)
            in_lines.append(f"      {pname}: {source}")

        # Collect this step's outputs for subsequent wiring
        for port in mod.get("outputs", []):
            pname = _safe_id(port.get("name", ""))
            prev_outputs[pname] = f"{step_id}/{pname}"

        out_ids = " ".join(_safe_id(p.get("name", "")) for p in mod.get("outputs", []))
        in_block = "\n".join(in_lines) if in_lines else "      {}"
        step_lines.append(f"""
  {step_id}:
    run: {tool_ref}
    in:
{in_block}
    out: [{out_ids}]""")

    wi_block = "\n".join(wi_lines) if wi_lines else "  {}"
    wo_block = "\n".join(wo_lines) if wo_lines else "  {}"

    return f"""\
#!/usr/bin/env cwl-runner
# CWL v1.2 Workflow — SensorWF
# Auto-generated by scripts/utils/cwl_export.py
#
# Run with:
#   cwltool workflow.cwl --raw_files path/to/data.csv

cwlVersion: v1.2
class: Workflow

label: "SensorWF: Sensor Workflow Framework"
doc: >
  A FAIR generalizable workflow framework for multi-domain scientific
  time-series analysis.  Modules M1-M5 form the reusable core;
  E1/E2 are anomaly-detection use-case extensions.

requirements:
  SubworkflowFeatureRequirement: {{}}
  ScatterFeatureRequirement: {{}}

inputs:
{wi_block}

outputs:
{wo_block}

steps:
{"".join(step_lines)}
"""


# ── Main ──────────────────────────────────────────────────────────────────────

def export_cwl(
    components_path: str = "components.json",
    output_dir: str      = "cwl",
    include_extensions: bool = True,
) -> dict[str, str]:
    """
    Generate CWL files from components.json.

    Returns
    -------
    dict mapping logical name → file path for each generated file.
    """
    with open(components_path, "r", encoding="utf-8") as fh:
        spec = json.load(fh)

    modules = spec.get("modules", [])
    if not include_extensions:
        modules = [m for m in modules if not m.get("extension", False)]

    tools_dir = os.path.join(output_dir, "tools")
    os.makedirs(tools_dir, exist_ok=True)

    artifacts: dict[str, str] = {}

    # Per-module tool CWL files
    for mod in modules:
        mod_id      = mod["id"]
        script_path = mod.get("script_path") or mod.get("provone_uri", "").replace("sensorwf:", "")
        tool_cwl    = _make_tool_cwl(mod, script_path)
        out_path    = os.path.join(tools_dir, f"{mod_id}.cwl")
        with open(out_path, "w", encoding="utf-8") as fh:
            fh.write(tool_cwl)
        artifacts[f"tool:{mod_id}"] = out_path

    # Top-level workflow CWL
    wf_cwl   = _make_workflow_cwl(modules, tool_dir="tools")
    wf_path  = os.path.join(output_dir, "workflow.cwl")
    with open(wf_path, "w", encoding="utf-8") as fh:
        fh.write(wf_cwl)
    artifacts["workflow"] = wf_path

    return artifacts


def main() -> None:
    parser = argparse.ArgumentParser(description="Export SensorWF components to CWL")
    parser.add_argument("--components", default="components.json",
                        help="Path to components.json (default: components.json)")
    parser.add_argument("--output",     default="cwl",
                        help="Output directory (default: cwl/)")
    parser.add_argument("--core-only",  action="store_true",
                        help="Export only M1-M5 (skip E1/E2 extension modules)")
    args = parser.parse_args()

    artifacts = export_cwl(
        components_path=args.components,
        output_dir=args.output,
        include_extensions=not args.core_only,
    )
    print(f"[cwl_export] CWL files written to {args.output}/")
    for key, path in artifacts.items():
        print(f"  {key}: {path}")


if __name__ == "__main__":
    main()
