#!/usr/bin/env cwl-runner
# CWL v1.2 CommandLineTool — Fault Injection
# Auto-generated by scripts/utils/cwl_export.py

cwlVersion: v1.2
class: CommandLineTool

label: "Fault Injection"
doc: >
  Injects synthetic faults into clean sessions to produce labelled evaluation variants. Fault morphologies are drawn from domain-specific taxonomies. A three-tier difficulty system scales amplitude, duration, and channel spread simultaneously to avoid single-axis separability (Wu & Keogh 2022). Part of the anomaly detection use case only; not part of the reusable core.

baseCommand: [python, "FaultInjection"]

requirements:
  NetworkAccess:
    networkAccess: false

hints:
  SoftwareRequirement:
    packages:
      - package: sensorwf
        version: ["1.0.0"]

inputs:
  clean_df:
    type: File
    doc: "Standardised clean session from M1"
    inputBinding:
      prefix: --clean-df
  fault_types:
    type: string[]
    doc: "Domain fault taxonomy from adapter"
    inputBinding:
      prefix: --fault-types
  tiers:
    type: string
    doc: "Difficulty tiers: easy, medium, hard"
    inputBinding:
      prefix: --tiers
  n_variants:
    type: int
    doc: "Number of random variants per (type, tier) pair"
    inputBinding:
      prefix: --n-variants
  seed:
    type: int
    doc: "Random seed for reproducibility"
    inputBinding:
      prefix: --seed

outputs:
  injected_csvs:
    type: string[]
    doc: "One CSV per (fault_type, tier, variant) labelled with anomaly start/end"
    outputBinding:
      glob: 'injected_csvs*'
  label_csvs:
    type: string[]
    doc: "Corresponding label files with start_idx, end_idx, severity"
    outputBinding:
      glob: 'label_csvs*'
  injection_summary:
    type: File
    doc: "Summary table of all injected variants"
    outputBinding:
      glob: 'injection_summary*'

# Config parameters (passed as --key value at runtime)
# Defaults:
#   --tiers ['easy', 'medium', 'hard']  # Difficulty tiers to generate
#   --n-variants 2  # Variants per (fault_type, tier) pair
#   --seed 42  # Master random seed

