#!/usr/bin/env cwl-runner
# CWL v1.2 CommandLineTool — Anomaly Detection
# Auto-generated by scripts/utils/cwl_export.py

cwlVersion: v1.2
class: CommandLineTool

label: "Anomaly Detection"
doc: >
  Trains five ML detectors on the first 60% clean prefix; evaluates on injected suffix. Detectors: ZScore (MAD-robust), RobustRollingZScore (CUSUM), IsolationForest (rotation ensemble), Autoencoder (multi-scale MLP), LOF (density-based novelty). Threshold strategy: EVT/POT GPD calibration for density detectors; 99th-pct for statistical detectors. Part of the anomaly detection use case only; not part of the reusable core.

baseCommand: [python, "AnomalyDetection"]

requirements:
  NetworkAccess:
    networkAccess: false

hints:
  SoftwareRequirement:
    packages:
      - package: sensorwf
        version: ["1.0.0"]

inputs:
  X_clean:
    type: File
    doc: "Feature matrix of clean session (M3 output)"
    inputBinding:
      prefix: --X-clean
  injected_dir:
    type: File
    doc: "Directory of injected CSV files (E1 output)"
    inputBinding:
      prefix: --injected-dir
  files_generated:
    type: string[]
    doc: "List of (tag, tier, variant) tuples from E1"
    inputBinding:
      prefix: --files-generated

outputs:
  ml_results:
    type: string[]
    doc: "Per-(tag, tier, variant, detector) metrics"
    outputBinding:
      glob: 'ml_results*'
  ml_metrics_by_tier:
    type: File
    doc: "Aggregated metrics by tier and detector"
    outputBinding:
      glob: 'ml_metrics_by_tier*'
  if_feature_importances:
    type: File
    doc: "IsolationForest feature importance vector"
    outputBinding:
      glob: 'if_feature_importances*'

# Config parameters (passed as --key value at runtime)
# Defaults:
#   --train-frac 0.6  # Fraction of clean session for training
#   --threshold-pct 99.0  # Percentile of training scores for threshold (statistical detectors)
#   --threshold-strategy evt_for_density  # Threshold calibration: percentile | evt_for_density (GPD POT for IF/LOF)
#   --n-estimators-if 300  # Number of trees in IsolationForest ensemble
#   --lof-n-neighbors 20  # Local Outlier Factor neighbourhood size
#   --evt-pre-pct 90.0  # POT pre-threshold percentile for EVT GPD tail fit
#   --evt-exceedance-prob 0.01  # Target exceedance probability for EVT return level
#   --ae-seq-len 8  # Autoencoder temporal window length
#   --ae-denoise-sigma 0.06  # Denoising noise standard deviation for Autoencoder

