#!/usr/bin/env cwl-runner
# CWL v1.2 CommandLineTool — Data Ingestion
# Auto-generated by scripts/utils/cwl_export.py

cwlVersion: v1.2
class: CommandLineTool

label: "Data Ingestion"
doc: >
  Domain-adaptive ingestion that normalises raw sensor archives into a standardised time-series DataFrame (timestamp, elapsed_s, numeric channels). Each domain is handled by a pluggable DomainAdapter implementing the shared interface.

baseCommand: [python, "DataIngestion"]

requirements:
  NetworkAccess:
    networkAccess: false

hints:
  SoftwareRequirement:
    packages:
      - package: sensorwf
        version: ["1.0.0"]

inputs:
  raw_files:
    type: File
    doc: "Raw sensor archive (SCOTTI v2 CSV, MIT-BIH CSV, Jena Climate CSV)"
    inputBinding:
      prefix: --raw-files
  adapter_config:
    type: string
    doc: "Domain adapter parameters (target_hz, session_minutes, year, etc.)"
    inputBinding:
      prefix: --adapter-config

outputs:
  clean_df:
    type: File
    doc: "Standardised time-series with timestamp, elapsed_s, and sensor channels"
    outputBinding:
      glob: 'clean_df*'
  adapter_meta:
    type: File
    doc: "Adapter name, channels, native_hz, session length"
    outputBinding:
      glob: 'adapter_meta*'

# Config parameters (passed as --key value at runtime)
# Defaults:
#   --session-minutes 5.0  # Session duration in minutes for ECG records
#   --year 2011  # Calendar year to extract for Climate domain
#   --months [1, 6]  # Start/end months for Climate slice

