#!/usr/bin/env cwl-runner
# CWL v1.2 CommandLineTool — Quality Assessment
# Auto-generated by scripts/utils/cwl_export.py

cwlVersion: v1.2
class: CommandLineTool

label: "Quality Assessment"
doc: >
  Domain-agnostic sensor quality audit: NaN rates, stuck-channel detection, timing regularity, per-channel z-score flagging, and linear trend detection on selected channels. Outputs a machine-readable JSON quality report.

baseCommand: [python, "QualityAssessment"]

requirements:
  NetworkAccess:
    networkAccess: false

hints:
  SoftwareRequirement:
    packages:
      - package: sensorwf
        version: ["1.0.0"]

inputs:
  clean_df:
    type: File
    doc: "Standardised time-series from M1"
    inputBinding:
      prefix: --clean-df
  channels:
    type: string
    doc: "Sensor channels to assess"
    inputBinding:
      prefix: --channels
  config:
    type: string
    doc: "Domain quality-assessment config (thresholds, expected dt, trend channels)"
    inputBinding:
      prefix: --config

outputs:
  quality_report:
    type: File
    doc: "Per-channel quality metrics and summary flags"
    outputBinding:
      glob: 'quality_report*'

# Config parameters (passed as --key value at runtime)
# Defaults:
#   --stuck-unique-max 3  # Maximum unique values for a channel to be flagged as stuck
#   --zscore-threshold 3.0  # Sigma threshold for per-channel z-score flagging
#   --gap-multiplier 5.0  # Multiplier over expected_dt_s to define a large timing gap
#   --trend-channels []  # Channel names to run linear trend regression on

