#!/usr/bin/env cwl-runner
# CWL v1.2 CommandLineTool — Feature Engineering
# Auto-generated by scripts/utils/cwl_export.py

cwlVersion: v1.2
class: CommandLineTool

label: "Feature Engineering"
doc: >
  Builds a multi-dimensional feature matrix from the clean time-series. Nine feature families per channel (when session >= 3x window): (1) raw value, (2) first-order difference, (3) rolling mean, (4) rolling std, (5) rolling skewness, (6) rolling excess kurtosis, (7) zero-crossing rate, (8) spectral entropy, (9) dominant frequency (Hz). Plus a sample-interval timing feature (dt_sample).

baseCommand: [python, "scripts/pipeline_core.py"]

requirements:
  NetworkAccess:
    networkAccess: false

hints:
  SoftwareRequirement:
    packages:
      - package: sensorwf
        version: ["1.0.0"]

inputs:
  clean_df:
    type: File
    doc: "Standardised time-series from M1"
    inputBinding:
      prefix: --clean-df
  channels:
    type: string
    doc: "Sensor channels to engineer features over"
    inputBinding:
      prefix: --channels
  window:
    type: int
    doc: "Rolling window size in samples"
    inputBinding:
      prefix: --window

outputs:
  X:
    type: File
    doc: "Feature matrix (n_samples, n_features)"
    outputBinding:
      glob: 'X*'
  feature_names:
    type: File
    doc: "Name of each feature column"
    outputBinding:
      glob: 'feature_names*'

# Config parameters (passed as --key value at runtime)
# Defaults:
#   --window 15  # Rolling window size in samples

