#!/usr/bin/env cwl-runner
# CWL v1.2 CommandLineTool — Semantic Annotation
# Auto-generated by scripts/utils/cwl_export.py

cwlVersion: v1.2
class: CommandLineTool

label: "Semantic Annotation"
doc: >
  Maps ML detector evidence (feature importances, anomaly scores) and feature names to domain OWL ontology classes. Produces a SPARQL-queryable knowledge graph in RDF/Turtle and GraphML. In core mode, edges encode feature-class membership; in use-case mode, all five detector results are aggregated — IsolationForest importance-weighted edges plus per-detector performance nodes (AUC-ROC, F1, recall) and consensus evidence edges.

baseCommand: [python, "scripts/pipeline_core.py"]

requirements:
  NetworkAccess:
    networkAccess: false

hints:
  SoftwareRequirement:
    packages:
      - package: sensorwf
        version: ["1.0.0"]

inputs:
  feature_names:
    type: string
    doc: "Feature names from M3"
    inputBinding:
      prefix: --feature-names
  ontology_path:
    type: File
    doc: "Domain OWL ontology file"
    inputBinding:
      prefix: --ontology-path
  ml_results:
    type: string[]
    doc: "ML evaluation results from E2 (optional; enables importance-weighted edges)"
    inputBinding:
      prefix: --ml-results

outputs:
  kg_ttl:
    type: File
    doc: "Ontology-linked knowledge graph"
    outputBinding:
      glob: 'kg_ttl*'
  kg_graphml:
    type: File
    doc: "Knowledge graph in GraphML for visualisation"
    outputBinding:
      glob: 'kg_graphml*'
  nodes_csv:
    type: File
    doc: "KG node table"
    outputBinding:
      glob: 'nodes_csv*'
  edges_csv:
    type: File
    doc: "KG edge table"
    outputBinding:
      glob: 'edges_csv*'
  if_interpretability_report:
    type: File
    doc: "Human-readable IsolationForest feature importance report listing top-N features with importance scores and ontology class mappings"
    outputBinding:
      glob: 'if_interpretability_report*'

# Config parameters (passed as --key value at runtime)
# Defaults:
#   --min-importance 0.001  # Minimum feature importance to include edge in KG

