#!/usr/bin/env cwl-runner
# CWL v1.2 CommandLineTool — Provenance Export
# Auto-generated by scripts/utils/cwl_export.py

cwlVersion: v1.2
class: CommandLineTool

label: "Provenance Export"
doc: >
  Records one prov:Activity per M1-M4 module execution with wall-clock timestamps, input row counts, output file paths, and parameter values. Serialises the complete PROV-O/ProvONE trace to RDF/Turtle.

baseCommand: [python, "ProvenanceExport"]

requirements:
  NetworkAccess:
    networkAccess: false

hints:
  SoftwareRequirement:
    packages:
      - package: sensorwf
        version: ["1.0.0"]

inputs:
  activity_records:
    type: string[]
    doc: "One dict per module execution (ProvenanceRecorder.record_activity)"
    inputBinding:
      prefix: --activity-records

outputs:
  provenance_ttl:
    type: File
    doc: "Complete PROV-O/ProvONE provenance trace for the run"
    outputBinding:
      glob: 'provenance_ttl*'

# Config parameters (passed as --key value at runtime)
# Defaults:
#   --output-path results/provenance.ttl  # Output Turtle file path
#   --sha256-inputs True  # Compute SHA-256 checksums for output file entities (always-on; stored as telwf:sha256 in provenance Turtle)

