#!/usr/bin/env cwl-runner
# CWL v1.2 Workflow — SensorWF
# Auto-generated by scripts/utils/cwl_export.py
#
# Run with:
#   cwltool workflow.cwl --raw_files path/to/data.csv

cwlVersion: v1.2
class: Workflow

label: "SensorWF: Sensor Workflow Framework"
doc: >
  A FAIR generalizable workflow framework for multi-domain scientific
  time-series analysis.  Modules M1-M5 form the reusable core;
  E1/E2 are anomaly-detection use-case extensions.

requirements:
  SubworkflowFeatureRequirement: {}
  ScatterFeatureRequirement: {}

inputs:
  raw_files:
    type: [File, "null"]
    doc: "Raw sensor archive (SCOTTI v2 CSV, MIT-BIH CSV, Jena Climate CSV)"
  adapter_config:
    type: [string, "null"]
    doc: "Domain adapter parameters (target_hz, session_minutes, year, etc.)"
  channels:
    type: [string, "null"]
    doc: "Sensor channels to assess"
  config:
    type: [string, "null"]
    doc: "Domain quality-assessment config (thresholds, expected dt, trend channels)"
  window:
    type: [int, "null"]
    doc: "Rolling window size in samples"
  ontology_path:
    type: [File, "null"]
    doc: "Domain OWL ontology file"
  ml_results:
    type: [string[], "null"]
    doc: "ML evaluation results from E2 (optional; enables importance-weighted edges)"
  activity_records:
    type: [string[], "null"]
    doc: "One dict per module execution (ProvenanceRecorder.record_activity)"
  fault_types:
    type: [string[], "null"]
    doc: "Domain fault taxonomy from adapter"
  tiers:
    type: [string, "null"]
    doc: "Difficulty tiers: easy, medium, hard"
  n_variants:
    type: [int, "null"]
    doc: "Number of random variants per (type, tier) pair"
  seed:
    type: [int, "null"]
    doc: "Random seed for reproducibility"
  X_clean:
    type: [File, "null"]
    doc: "Feature matrix of clean session (M3 output)"
  injected_dir:
    type: [File, "null"]
    doc: "Directory of injected CSV files (E1 output)"
  files_generated:
    type: [string[], "null"]
    doc: "List of (tag, tier, variant) tuples from E1"

outputs:
  ml_results:
    type: File
    outputSource: E2/ml_results
  ml_metrics_by_tier:
    type: File
    outputSource: E2/ml_metrics_by_tier
  if_feature_importances:
    type: File
    outputSource: E2/if_feature_importances

steps:

  M1:
    run: tools/M1.cwl
    in:
      raw_files: raw_files
      adapter_config: adapter_config
    out: [clean_df adapter_meta]
  M2:
    run: tools/M2.cwl
    in:
      clean_df: M1/clean_df
      channels: channels
      config: config
    out: [quality_report]
  M3:
    run: tools/M3.cwl
    in:
      clean_df: M1/clean_df
      channels: channels
      window: window
    out: [X feature_names]
  M4:
    run: tools/M4.cwl
    in:
      feature_names: M3/feature_names
      ontology_path: ontology_path
      ml_results: ml_results
    out: [kg_ttl kg_graphml nodes_csv edges_csv if_interpretability_report]
  M5:
    run: tools/M5.cwl
    in:
      activity_records: activity_records
    out: [provenance_ttl]
  E1:
    run: tools/E1.cwl
    in:
      clean_df: M1/clean_df
      fault_types: fault_types
      tiers: tiers
      n_variants: n_variants
      seed: seed
    out: [injected_csvs label_csvs injection_summary]
  E2:
    run: tools/E2.cwl
    in:
      X_clean: X_clean
      injected_dir: injected_dir
      files_generated: files_generated
    out: [ml_results ml_metrics_by_tier if_feature_importances]
