/* Auto-generated by phase3_quantization.py — DO NOT EDIT */
#pragma once
#include <stdint.h>

#define IDS_N_NODES    51
#define IDS_N_FEATURES 34
#define IDS_QMAX       127

static const int16_t ids_feature[51] = {
    10, 9, 1, 28, -2, -2, 23, 11, -2, -2, 7, -2, -2, 24, 24, 17, -2, -2, 6, -2, -2, 28, 28, -2, -2, 24, -2, -2, 23, 6, 25, -2, -2, 29, 24, -2, -2, 25, -2, -2, 13, 5, -2, -2, 24, 28, -2, -2, 19, -2, -2
};

static const int8_t ids_threshold[51] = {
    0, 1, 8, 11, 0, 0, 0, 0, 0, 0, 0, 0, 0, 26, 2, 58, 0, 0, 0, 0, 0, 4, 1, 0, 0, 44, 0, 0, 0, 0, 38, 0, 0, 4, 66, 0, 0, 50, 0, 0, 0, 0, 0, 0, 85, 10, 0, 0, 86, 0, 0
};

static const int16_t ids_left[51] = {
    1, 2, 3, 4, -1, -1, 7, 8, -1, -1, 11, -1, -1, 14, 15, 16, -1, -1, 19, -1, -1, 22, 23, -1, -1, 26, -1, -1, 29, 30, 31, -1, -1, 34, 35, -1, -1, 38, -1, -1, 41, 42, -1, -1, 45, 46, -1, -1, 49, -1, -1
};

static const int16_t ids_right[51] = {
    28, 13, 6, 5, -1, -1, 10, 9, -1, -1, 12, -1, -1, 21, 18, 17, -1, -1, 20, -1, -1, 25, 24, -1, -1, 27, -1, -1, 40, 33, 32, -1, -1, 37, 36, -1, -1, 39, -1, -1, 44, 43, -1, -1, 48, 47, -1, -1, 50, -1, -1
};

static const int8_t ids_leaf_class[51] = {
    -1, -1, -1, -1, 0, 1, -1, -1, 1, 0, -1, 0, 1, -1, -1, -1, 1, 0, -1, 1, 1, -1, -1, 1, 1, -1, 0, 1, -1, -1, -1, 1, 0, -1, -1, 0, 1, -1, 0, 1, -1, -1, 0, 0, -1, -1, 1, 1, -1, 0, 1
};

static const float ids_feat_min[34] = {
    -0.208680f, -5.158630f, 0.000000f, -2.638517f, -0.138121f, -0.165331f, -0.049173f, -0.098409f, -0.569112f, -0.380167f, -0.272850f, -0.074561f, -0.125576f, -0.131795f, -0.090412f, -0.110522f, -0.148150f, -0.955926f, -0.735580f, -0.734888f, -0.937314f, -0.495523f, -0.439166f, -0.489097f, -0.532485f, -0.478859f, -0.143883f, -0.039675f, -0.519345f, -0.520051f, -0.110419f, -0.110372f, -0.193597f, -0.120335f
};

static const float ids_feat_scale[34] = {
    0.079079f, 0.048683f, 0.007874f, 0.070984f, 0.556899f, 0.771611f, 0.587479f, 0.789322f, 0.049107f, 0.253860f, 0.073188f, 0.576729f, 0.804086f, 0.095974f, 0.408199f, 0.234526f, 0.579787f, 0.015764f, 0.024725f, 0.024796f, 0.015781f, 0.213478f, 0.307080f, 0.261641f, 0.056445f, 0.045191f, 1.905921f, 1.040566f, 0.048243f, 0.060761f, 0.271306f, 0.270536f, 0.346439f, 0.066381f
};

/* Quantized inference — call with a raw float feature vector */
static inline int ids_predict(const float *x) {
    int8_t xq[IDS_N_FEATURES];
    for (int i = 0; i < IDS_N_FEATURES; i++) {
        float q = (x[i] - ids_feat_min[i]) / ids_feat_scale[i];
        if (q > IDS_QMAX) q = IDS_QMAX;
        if (q < -IDS_QMAX) q = -IDS_QMAX;
        xq[i] = (int8_t)q;
    }
    int16_t node = 0;
    while (ids_feature[node] >= 0) {
        int16_t f = ids_feature[node];
        if (xq[f] <= ids_threshold[node])
            node = ids_left[node];
        else
            node = ids_right[node];
    }
    return ids_leaf_class[node];
}
