/* Auto-generated by generate_scaler_header.py — DO NOT EDIT */
#pragma once
#include <stdint.h>

#define IDS_N_FEATURES 15

/* Feature index constants */
#define IDS_FEAT_CAN_ID_NORM                    0
#define IDS_FEAT_DLC                            1
#define IDS_FEAT_DATA_MEAN                      2
#define IDS_FEAT_DATA_STD                       3
#define IDS_FEAT_DATA_ENTROPY                   4
#define IDS_FEAT_DATA_RANGE                     5
#define IDS_FEAT_HAMMING_DIST                   6
#define IDS_FEAT_INTER_ARRIVAL_MEAN             7
#define IDS_FEAT_INTER_ARRIVAL_STD              8
#define IDS_FEAT_ID_FREQ                        9
#define IDS_FEAT_BUS_LOAD                       10
#define IDS_FEAT_UNIQUE_IDS                     11
#define IDS_FEAT_DLC_ANOMALY                    12
#define IDS_FEAT_ID_IS_KNOWN                    13
#define IDS_FEAT_PAYLOAD_DELTA                  14

/* StandardScaler parameters (fit on training data) */
static const float ids_scaler_mean[15] = {
    0.376404f, 6.833333f, 35.634544f, 56.605396f, 0.955393f, 144.781586f, 10.190434f, 0.007000f, 0.000000f, 157.452103f, 874.693542f, 5.999917f, 0.000000f, 1.000000f, 276.030884f
};

static const float ids_scaler_scale[15] = {
    0.000834f, 2.608746f, 33.157360f, 46.228394f, 0.720550f, 114.589386f, 10.869287f, 0.000040f, 0.000000f, 2.494435f, 6.964801f, 0.017480f, 1.000000f, 1.000000f, 344.548889f
};

/* Apply StandardScaler in-place to a raw feature vector */
static inline void ids_scale_features(float *x) {
    for (int i = 0; i < IDS_N_FEATURES; i++) {
        x[i] = (x[i] - ids_scaler_mean[i]) / ids_scaler_scale[i];
    }
}
