/* Auto-generated by phase3_quantization.py — DO NOT EDIT */
#pragma once
#include <stdint.h>

#define IDS_N_NODES    63
#define IDS_N_FEATURES 15
#define IDS_QMAX       32767

static const int16_t ids_feature[63] = {
    2, 3, 0, 3, 3, -2, -2, 4, -2, -2, 5, 1, -2, -2, 0, -2, -2, 4, 1, 3, -2, -2, 2, -2, -2, 5, 2, -2, -2, 0, -2, -2, 0, 4, 3, 2, -2, -2, 6, -2, -2, 3, 2, -2, -2, 3, -2, -2, 4, 2, 2, -2, -2, 2, -2, -2, 2, 3, -2, -2, 4, -2, -2
};

static const int16_t ids_threshold[63] = {
    19061, 20515, 9830, 12827, 12032, 0, 0, 20479, 0, 0, 2634, 16384, 0, 0, 16383, 0, 0, 20299, 16384, 21546, 0, 0, 15931, 0, 0, 32574, 10943, 0, 0, 13107, 0, 0, 22937, 15868, 32751, 19183, 0, 0, 28324, 0, 0, 27741, 20186, 0, 0, 29193, 0, 0, 19449, 24991, 19208, 0, 0, 27583, 0, 0, 23181, 28994, 0, 0, 20299, 0, 0
};

static const int16_t ids_left[63] = {
    1, 2, 3, 4, 5, -1, -1, 8, -1, -1, 11, 12, -1, -1, 15, -1, -1, 18, 19, 20, -1, -1, 23, -1, -1, 26, 27, -1, -1, 30, -1, -1, 33, 34, 35, 36, -1, -1, 39, -1, -1, 42, 43, -1, -1, 46, -1, -1, 49, 50, 51, -1, -1, 54, -1, -1, 57, 58, -1, -1, 61, -1, -1
};

static const int16_t ids_right[63] = {
    32, 17, 10, 7, 6, -1, -1, 9, -1, -1, 14, 13, -1, -1, 16, -1, -1, 25, 22, 21, -1, -1, 24, -1, -1, 29, 28, -1, -1, 31, -1, -1, 48, 41, 38, 37, -1, -1, 40, -1, -1, 45, 44, -1, -1, 47, -1, -1, 56, 53, 52, -1, -1, 55, -1, -1, 60, 59, -1, -1, 62, -1, -1
};

static const int8_t ids_leaf_class[63] = {
    -1, -1, -1, -1, -1, 1, 0, -1, 1, 1, -1, -1, 0, 0, -1, 1, 0, -1, -1, -1, 0, 1, -1, 0, 1, -1, -1, 0, 0, -1, 0, 1, -1, -1, -1, -1, 1, 1, -1, 1, 0, -1, -1, 0, 1, -1, 1, 1, -1, -1, -1, 0, 1, -1, 0, 1, -1, -1, 0, 0, -1, 0, 1
};

static const float ids_feat_min[15] = {
    -1.463850f, -2.236068f, -1.074710f, -1.224473f, -1.325923f, -1.263482f, -0.937544f, -173.202194f, -1.909835f, -62.720463f, -125.444153f, -286.037262f, 0.000000f, 0.000000f, -0.801137f
};

static const float ids_feat_scale[15] = {
    0.000089f, 0.000082f, 0.000154f, 0.000084f, 0.000127f, 0.000068f, 0.000166f, 0.005286f, 0.000092f, 0.012222f, 0.008759f, 0.008730f, 0.000031f, 0.000031f, 0.000160f
};

/* Quantized inference — call with a raw float feature vector */
static inline int ids_predict(const float *x) {
    int16_t xq[IDS_N_FEATURES];
    for (int i = 0; i < IDS_N_FEATURES; i++) {
        float q = (x[i] - ids_feat_min[i]) / ids_feat_scale[i];
        if (q > IDS_QMAX) q = IDS_QMAX;
        if (q < -IDS_QMAX) q = -IDS_QMAX;
        xq[i] = (int16_t)q;
    }
    int16_t node = 0;
    while (ids_feature[node] >= 0) {
        int16_t f = ids_feature[node];
        if (xq[f] <= ids_threshold[node])
            node = ids_left[node];
        else
            node = ids_right[node];
    }
    return ids_leaf_class[node];
}
