/* Auto-generated by phase3_quantization.py — DO NOT EDIT */
#pragma once
#include <stdint.h>

#define IDS_N_NODES    61
#define IDS_N_FEATURES 15
#define IDS_QMAX       32767

static const int16_t ids_feature[61] = {
    5, 4, 2, 3, 0, -2, -2, 4, -2, -2, 2, 3, -2, -2, 4, -2, -2, 8, 14, 8, -2, -2, 2, -2, -2, 14, 0, -2, -2, 2, -2, -2, 4, 0, 4, 2, -2, -2, 14, -2, -2, 6, 4, -2, -2, 2, -2, -2, 3, 0, -2, 3, -2, -2, 3, 2, -2, -2, 4, -2, -2
};

static const int16_t ids_threshold[61] = {
    32703, 22695, 6178, 18549, 16131, 0, 0, 15551, 0, 0, 7980, 20079, 0, 0, 18015, 0, 0, 22005, 32, 17973, 0, 0, 10629, 0, 0, 53, 16131, 0, 0, 6115, 0, 0, 24060, 32452, 12889, 5797, 0, 0, 32, 0, 0, 24203, 22695, 0, 0, 20262, 0, 0, 24652, 32389, 0, 23788, 0, 0, 26062, 19446, 0, 0, 25425, 0, 0
};

static const int16_t ids_left[61] = {
    1, 2, 3, 4, 5, -1, -1, 8, -1, -1, 11, 12, -1, -1, 15, -1, -1, 18, 19, 20, -1, -1, 23, -1, -1, 26, 27, -1, -1, 30, -1, -1, 33, 34, 35, 36, -1, -1, 39, -1, -1, 42, 43, -1, -1, 46, -1, -1, 49, 50, -1, 52, -1, -1, 55, 56, -1, -1, 59, -1, -1
};

static const int16_t ids_right[61] = {
    32, 17, 10, 7, 6, -1, -1, 9, -1, -1, 14, 13, -1, -1, 16, -1, -1, 25, 22, 21, -1, -1, 24, -1, -1, 29, 28, -1, -1, 31, -1, -1, 48, 41, 38, 37, -1, -1, 40, -1, -1, 45, 44, -1, -1, 47, -1, -1, 54, 51, -1, 53, -1, -1, 58, 57, -1, -1, 60, -1, -1
};

static const int8_t ids_leaf_class[61] = {
    -1, -1, -1, -1, -1, 1, 1, -1, 0, 1, -1, -1, 1, 1, -1, 0, 1, -1, -1, -1, 1, 1, -1, 0, 1, -1, -1, 0, 0, -1, 0, 1, -1, -1, -1, -1, 1, 1, -1, 1, 0, -1, -1, 0, 0, -1, 1, 0, -1, -1, 1, -1, 0, 0, -1, -1, 1, 0, -1, 0, 1
};

static const float ids_feat_min[15] = {
    -2.235867f, -2.236068f, -0.780591f, -0.959161f, -1.353482f, -0.988743f, -0.839189f, -346.408752f, -1.287889f, -165.346725f, -546.909485f, -572.076782f, 0.000000f, 0.000000f, -0.530637f
};

static const float ids_feat_scale[15] = {
    0.000083f, 0.000082f, 0.000214f, 0.000105f, 0.000110f, 0.000078f, 0.000169f, 0.010572f, 0.000080f, 0.027596f, 0.032730f, 0.017459f, 0.000031f, 0.000031f, 0.000214f
};

/* Quantized inference — call with a raw float feature vector */
static inline int ids_predict(const float *x) {
    int16_t xq[IDS_N_FEATURES];
    for (int i = 0; i < IDS_N_FEATURES; i++) {
        float q = (x[i] - ids_feat_min[i]) / ids_feat_scale[i];
        if (q > IDS_QMAX) q = IDS_QMAX;
        if (q < -IDS_QMAX) q = -IDS_QMAX;
        xq[i] = (int16_t)q;
    }
    int16_t node = 0;
    while (ids_feature[node] >= 0) {
        int16_t f = ids_feature[node];
        if (xq[f] <= ids_threshold[node])
            node = ids_left[node];
        else
            node = ids_right[node];
    }
    return ids_leaf_class[node];
}
